fix: no service found for - "org.qt-project.qt.audiosource"
linuxdeepin/deepin-voice-recorder pull request #5
Opened 2019-04-05 12:48 UTC by PikachuHy

defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.audiosource"
support codecs: ()
support containers: ()

2019-04-16 03:04 UTC, BLumia commented
``` plain
make[1]: Entering directory '/build/deepin-voice-recorder-1.3.9~pulls~5'
dh_auto_configure -- DEFINES+="VERSION=1.3.9~pulls~5"
	cd obj-x86_64-linux-gnu && cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON "-GUnix Makefiles" DEFINES\+=VERSION=1.3.9\~pulls\~5
Can't exec "cmake": No such file or directory at /usr/share/perl5/Debian/Debhelper/Dh_Lib.pm line 459.
dh_auto_configure: cd obj-x86_64-linux-gnu && cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON "-GUnix Makefiles" DEFINES\+=VERSION=1.3.9\~pulls\~5 failed to execute: No child processes
dh_auto_configure: cd obj-x86_64-linux-gnu && cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON "-GUnix Makefiles" DEFINES\+=VERSION=1.3.9\~pulls\~5 returned exit code 2
make[1]: *** [debian/rules:11: override_dh_auto_configure] Error 2
make[1]: Leaving directory '/build/deepin-voice-recorder-1.3.9~pulls~5'
make: *** [debian/rules:8: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
E: Failed autobuilding of package
```

`cmake` 支持应该漏掉写 `cmake` 的构建依赖了的样子，考虑给 `debian/control` 构建依赖改成 `cmake` 或者指定构建系统使用 `qmake` 都可以。

2019-04-16 03:07 UTC, BLumia requested changes
考虑把 cmake 支持的提交分到另一个 PR 吧，这样可以先合第一个（

2019-04-17 04:10 UTC, PikachuHy commented
@BLumia  我cmake的commit强制取消调了，cmake的东西我后面再弄吧，最近没啥时间玩
这个录音的依赖问题，可以先合吧？

2019-04-17 05:12 UTC, BLumia approved these changes

2019-04-17 06:06 UTC, merged